### PR TITLE
Fix url generation to git hosted Cargo.toml file

### PR DESCRIPTION
**Pull request by paolobarbolini**
Property fixes urls containing `//`, which makes APIs return a redirect, breaking hyper since it can't follow them.

### CODE REVIEW

**Comment by robjtede** [comment]
Is there an example url to hit to test this?

**Comment by Enet4** [comment]
I can attest that this happens with the analysis of most repositories.

Example: http://localhost:8080/repo/github/deps-rs/deps.rs

Log output:

```json
{"msg":"error: Status code 301 Moved Permanently for URI https://raw.githubusercontent.com/deps-rs/deps.rs/HEAD//Cargo.toml","level":"ERRO","ts":"2020-10-01T16:30:09.051622+01:00","http_path":"/repo/github/deps-rs/deps.rs","version":"0.1.0"}
```

I would have opted for removing extraneous forward slashes after `HEAD/`, but this might be more reliable.

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
now that the tests are added, it does rather seem like there could be some deduplication across these files

**Comment by paolobarbolini** [comment]
Having a separate module just for url generation probably didn't make sense. This should work better and avoid a lot of duplication

**Comment by Feliix42** [comment]
We should definitely avoid this unnecessary redirect as it causes a relatively large performance overhead that is just not necessary. (although we should be able to follow 301 redirects, as some repositories could be moved)

**Review by Feliix42 — APPROVED** [review]

**Comment by robjtede** [comment]
Could experiment with switching out the client (to eg reqwest) since it might be easier to support 301s.

**Comment by Feliix42** [comment]
Yeah, that would probably nice. At the same time it was cool that we were able to use hyper for both the server and the http client (less dependencies), though that's just a nice side effect. But there may also be more efficient/ergonomic choices for the server side by now, I don't know.

**Comment by est31** [comment]
Thanks for the merge! The repo links still show up the known problem. When will the change be deployed?

https://deps.rs/repo/github/est31/rcgen

**Comment by Feliix42** [comment]
Hey, we just took over the project a few days ago and are still in the process of migrating the deployment, so it may take another couple of days until the change is live. If you want you can subscribe to #46. Once that's closed changes are going to be rolled out to the website automatically again.

**Comment by est31** [comment]
@Feliix42 thanks for the reply. Will subscribe to the issue! Glad to see the project being in good hands again.

**Pull request merged**
