### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by robjtede**
Bumps most dependencies to their latest versions and modernizes code to 2018 edition.

A non-goal of this PR is to update futures dependent crates to 0.3 ecosystem. I'm part way through doing it but it is about as much work to do as this PR.

This PR seems to retain the same capabilities of current deps.rs deployment. It's also clear that many more tests are needed.

Supercedes #42 & #31

### CODE REVIEW

**Review by cecton — COMMENTED** [review]
For me as long as it deploys the same it is fine but I haven't done any for the CI/CD yet. I think it is best someone familiar with the code review it

**Review by Feliix42 — APPROVED** [review]
I had a glimpse at the changes and form what I see, they are looking good. I sadly also do not yet have the deep insight into the code required to determine if this PR is indeed not breaking anything, but I tested it locally and from what I saw there was nothing broken that isn't also broken in the deployed version.

But I agree, some tests would be nice.

**Comment by robjtede** [comment]
Not to be too blasé, but I think there's value in just getting this modernization out of the way so that it's much easier to scrutinize and develop on. I'll let someone else merge if they feel happy doing so.

**Comment by Feliix42** [comment]
Yeah, given the current state of the project I also don't see why we shouldn't merge this right away to get started on the other things that are to be done.

**Comment by Enet4** [comment]
Allow me to just add a few points, as I was in the process of testing this on development environment when this was merged. No blockers from me regarding this PR anyway.

- I was bit by a known issue with this version of the crate `openssl`, as it doesn't work with the latest OpenSSL (https://github.com/sfackler/rust-openssl#987). This only means that we have room for more iterations with dependency updates, and I might as well see what I can do here.
- The project still seems to requires a nightly toolchain. How about we set up a fixed toolchain version that is sure to work? Although we are interested in pushing to work on stable once possible, setting this up is quick and could prevent surprises.

**Comment by paolobarbolini** [comment]
> I was bit by a known issue with this version of the crate openssl, as it doesn't work with the latest OpenSSL

I'm having the same issue. I could upgrade hyper to 0.12, which depends on the latest `openssl`, if nobody else already started working on it yet.

**Comment by Enet4** [comment]
>I could upgrade hyper to 0.12, which depends on the latest openssl, if nobody else already started working on it yet.

@paolobarbolini All I did for the time being is assess the effort required for the update. It may require changing a good amount of code, but hopefully it should be easy for someone already familiar with the latest hyper API while peeking the [changelogs for 0.12](https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v0120-2018-06-01). So if you would like to commit to this, at least by me that would be fine and good!

**Comment by Feliix42** [comment]
Oh, seems that I was a little quick on merging this, I'm sorry. 😅

I think I can look into the Rust version thing, either to see whether we can move to stable easily or to fix the nightly version.

**Pull request merged**
